/**
 * Task 12: End-to-End Pipeline Resilience Test (Paper Mode).
 *
 * Instrumented (`androidTest`) harness that proves decision -> log -> reward
 * back-fill -> rollout assembly -> training job survives real timing,
 * scheduling, and process-death conditions, entirely with zero capital at
 * risk. Gated behind `BuildConfig.ENABLE_RESILIENCE_TEST_HARNESS`
 * (debug-only, see `app/build.gradle.kts`) so it can never ship, and
 * [PipelineResilienceTest] independently hard-asserts the same paper-mode
 * guarantee at runtime as a second line of defense.
 *
 * **Run via `scripts/run_pipeline_resilience_test.sh`**, which drives
 * [PipelineResilienceTest]'s three phases as separate `am instrument`
 * invocations with a real `adb shell am force-stop` + relaunch between
 * them - see that script and [PipelineResilienceTest]'s class kdoc. A bare
 * `./gradlew connectedDebugAndroidTest` will build and install correctly
 * but fails fast at phase B/C's pid-unchanged guard, by design, since no
 * real kill happens between test methods running in one instrumentation
 * session.
 *
 * **Adaptations vs. the original design doc, and their current status:**
 *
 * 1. **No formal `TradingMode` concept exists in this codebase (accepted,
 *    unchanged).** There's no `TradingModeStore`/`TradingMode.PAPER` enum
 *    to assert against - the live/paper distinction today is implicit:
 *    [org.example.syncora.agent.DecisionLoopScheduler] always dispatches
 *    through a `BitgetTradingRestClient` pinned to
 *    [org.example.syncora.bitget.BitgetEnvironment.LIVE], gated only by
 *    [org.example.syncora.bitget.RiskSettingsStore.autoTradingEnabled] and
 *    whatever credentials [org.example.syncora.bitget.BitgetLiveCredentialsStore]
 *    holds. This harness's zero-capital-risk guarantee is therefore
 *    asserted the only way that's actually true today: auto-trading
 *    disabled *and* no live credentials saved, re-checked in every phase's
 *    `@Before` (including after each relaunch), so no order this run
 *    produces can physically reach the exchange. A real `TradingMode`
 *    abstraction that routes decisionLoopScheduler through
 *    [org.example.syncora.bitget.PaperTradingRepository] instead is
 *    follow-up work this test doesn't attempt.
 * 2. **No injectable `ClockSource` (accepted, unchanged).**
 *    [org.example.syncora.agent.DecisionLoopScheduler]'s cadence is driven
 *    by real kline-close events off
 *    [org.example.syncora.bitget.TradingChartPipeline.klines], not by any
 *    clock the app owns - there's nothing to substitute a `SimulatedClock`
 *    into. [SimulatedClock] here is a test-side timestamp generator only,
 *    and ticks are advanced deterministically via
 *    [org.example.syncora.bitget.TradingChartPipeline.injectTestKline]
 *    rather than by advancing a shared clock. [ResiliencePhaseState]
 *    persists that generator's value across phases so the simulated
 *    timeline resumes correctly after each relaunch.
 * 3. **`stateVectorBuilder`/`liveTradingRepository` still hit real network**
 *    for balance/position (accepted, unchanged) - `BitgetKlineSocket`/
 *    `BitgetKlineRestClient` aren't behind an injectable interface. Left
 *    as-is deliberately: the design doc's own goal is validating behavior
 *    "over multi-day, realistic conditions...under real timing,
 *    scheduling"; only the *cadence* (kline closes) and the *training-job
 *    constraints* need synthetic control to make a multi-day run fit in a
 *    test timeout. Expect this suite to be flakier in CI than a fully
 *    hermetic test would be until those clients get interface seams.
 * 4. **Fixture `.tflite` model - resolved, with one manual step.**
 *    [PipelineResilienceTest] now actually loads
 *    `app/src/androidTest/assets/fixtures/dummy_policy_model.tflite` as the
 *    live model before phaseA runs (matching
 *    [org.example.syncora.ml.PolicyInferenceEngine]'s expected I/O
 *    signature), instead of hard-erroring. The asset itself still isn't
 *    generated by this harness or checked into this pass - producing a
 *    valid TFLite flatbuffer needs the TF toolchain, which this repo
 *    doesn't otherwise depend on. Run `scripts/generate_dummy_policy_model.py`
 *    once (`pip install tensorflow` first) to produce it before the first
 *    run; see that script's header for details.
 * 5. **The instrumentation process shares the app's process - resolved,
 *    by restructuring rather than by an isolation flag.** Standard
 *    `AndroidJUnitRunner` instrumentation runs inside the target app's own
 *    process (that's how `Instrumentation` gets direct access to the
 *    `Application`/`Activity` instances this harness reads), and neither
 *    the AndroidX Test Orchestrator nor any other stock test runner changes
 *    that for a single running test method - orchestration only isolates
 *    *between* test methods (fresh process per `am instrument` invocation),
 *    which is exactly the seam this harness now uses: the scenario is
 *    split into [PipelineResilienceTest.phaseA_day1DecisionsAndFundingSettlement],
 *    [PipelineResilienceTest.phaseB_survivesFirstKillAndResolvesDay2], and
 *    [PipelineResilienceTest.phaseC_survivesSecondKillAndTrainingJobSucceeds],
 *    each launched as its own instrumentation invocation by
 *    `scripts/run_pipeline_resilience_test.sh`, with the actual
 *    `adb shell am force-stop` + relaunch performed by that host-side
 *    script *between* invocations rather than by
 *    [ProcessKillSimulator] from inside a running test method. Cross-phase
 *    state (simulated clock, and the previous phase's pid as a guard
 *    against silently skipping the kill) is persisted via
 *    [ResiliencePhaseState] so each phase's `@Before` picks up exactly
 *    where the last one left off.
 */
package org.example.syncora.resilience
